### PR TITLE
Install composer on LAMP/LAPP by default

### PR DESCRIPTION
**Pull request by qrntz**
Resolves https://github.com/turnkeylinux/tracker/issues/527

### CODE REVIEW

**Comment by JedMeister** [comment]
:+1:

**Comment by alonswartz** [comment]
@JedMeister what is the status on this? Should we hold off on merging since you reassigned to 14.2?

**Comment by JedMeister** [comment]
Yes good call Alon. It'd be good to tidy up all the appliances (that install composer in the app repo) at the same time. That way it's more likely that things won't be forgotten or missed.

**Comment by JedMeister** [comment]
:+1:

**Pull request merged**
