### PR TITLE
mediaserver samba v17.0

### PR DESCRIPTION
**Pull request by qq7**

### CODE REVIEW

**Comment by qq7** [comment]
I'm yet to test it, but could be that closes https://github.com/turnkeylinux/tracker/issues/989

**Comment by JedMeister** [comment]
@qq7 - Nice one man! This looks great. Unfortunately, I have no idea about javascript though, so might wait until @OnGle has had a look before we merge.

**Review by OnGle — APPROVED** [review]
So we've discussed this breifly oob. I'm happy with this, @qq7 was going to see if a slightly more elegant fix would be possible, but given his time constraints, and the fact that this has been tested and works, I'm incline to merge.

**Comment by qq7** [comment]
@JedMeister
I've looked into this before with browser dev tools and couldn't trace anything that would suggest that session is being stored in cookies.

**Comment by JedMeister** [comment]
Cheers @qq7 - Ok, thanks.

**Review by Christie018 — COMMENTED** [review]
Code review of update for mediaserver samba shows updating of appliance refactoring in dialog_wrapper, and addition of json variable to help control user authentication. PR mergerd and tested already.

**Pull request merged**
