### PR TITLE
Make Samba handle sudoadmin

### PR DESCRIPTION
**Pull request by qrntz**
* sets the Samba admin user to «admin»
* sets the password
* deactivates the root user

Not sure if the number is right. Also, this is basically a version of https://github.com/turnkeylinux/common/blob/master/conf/samba-rootpass which proved to be sufficient.

### CODE REVIEW

**Comment by JedMeister** [comment]
Looks good to me :+1:

**Comment by JedMeister** [comment]
@alonswartz - Can you please have a quick look and merge this. 

Also it closes https://github.com/turnkeylinux/tracker/issues/523

**Comment by alonswartz** [comment]
@qrntz wouldn't it make sense to have just one samba-pass script which does the right thing instead of having two (rootpass and sudoadmin)?

We also might want to remove the unlocking of root in samba-rootpass?

**Comment by alonswartz** [comment]
I'm merging the PR, then we'll handle the proposed changes/fixes...

**Comment by alonswartz** [comment]
Sorry about that, please ignore my previous comments. I was mistakenly under the impression that the samba-rootpass was an inithook. We should be good to go....

**Pull request merged**
