### PR TITLE
Lock Rack version to 1.6.4 to match Jessie provided Ruby

### PR DESCRIPTION
**Pull request by qrntz**

### CODE REVIEW

**Comment by JedMeister** [comment]
Makes sense...

**Comment by alonswartz** [comment]
Aren't the later versions backwards compatible with the ruby jessie version?

If we really need to pin to a specific version, it might be a better idea to have a debian_version mapping to rack_version. This way, when we move to the stretch, the build will either break or will install the latest version (instead of the hardcoded jessie version).

**Comment by qrntz** [comment]
@alonswartz, apparently they're not. The dependency resolver for ```gem``` tries to pull in Rack of a version newer than the Ruby version in Jessie supports which results in a fail.

You raise a valid point. Not sure how best to detect the Debian version from conf though.

**Comment by alonswartz** [comment]
`fab/share/product.mk` exposes a few useful variables, one being `CODENAME` (for example: jessie). You can see an example of this in https://github.com/turnkeylinux/common/blob/master/conf/turnkey.d/apt

**Comment by qrntz** [comment]
Thanks Alon. Does this look OK?

**Comment by alonswartz** [comment]
@qrntz conf/rails looks good, but conf/rails-pgsql needs to be updated as well doesn't it?

**Comment by qrntz** [comment]
Sure.

**Pull request merged**
