### PR TITLE
upgrade tomcat 6 -> tomcat 7

### PR DESCRIPTION
**Pull request by SiKing**
This starts with no warnings.

### CODE REVIEW

**Comment by SiKing** [comment]
This needs https://github.com/turnkeylinux-apps/tomcat/pull/1

**Comment by SiKing** [comment]
I should have also mentioned: I built this on top of the TKLDev14rc1.

**Comment by JedMeister** [comment]
Great work but pity that I wasn't aware that you were working on this. It could have saved one of us the effort! :smile: 

Anyway, it looks like you've done the extra work (above and beyond what I had done already in #26) but unfortunately it conflicts. So we'll need to resolve that. It's possibly easier for you to merge upstream (including my commits) back into your code, then reissue a pull request for the diff...

Although I note that you are using the 'master' branch for your update. FWIW it's good practice to leave the master clean (i.e. just tracking upstream) and work in a dev branch (as per our [gitflow](https://github.com/turnkeylinux/tracker/blob/master/GITFLOW.rst). Besides making things cleaner, IMO it also makes it easier to deal with conflicts (like this).

**Comment by SiKing** [comment]
When I started working on this I just needed the appliance for a client. I did not like the alternatives (Bitnami), and so I dove into this. Initially I was not confident that I could get it done, hence I did not announce anything. The appliance is running fine for the client now, BTW.

As for the merging. I am not very familiar with git, more of a (old-school) SVN guy. In git I normally resolve conflicts by just overwriting everything with my changes, and then fix any problems. However, I have absolutely no idea how to do pull requests.

**Comment by JedMeister** [comment]
Well you did a fantastic job IMO! :+1: 

I know TurnKey pretty well and am fairly handy with general Debian stuff, but not so well versedon Tomcat setup. So I did the bare minimum to get a working appliance. Like I said it looks like you've gone a bit further (which is awesome!)

Anyway that's cool. I'll take care of fixing the merge issues. Easiest way for me to do that will be me combining your code with master, fixing the conflicts (if need be; often if you merge the other way it resolves itself) and then I'll issue a new pull request. That means this one will be closed, but your commits will still make it in! :smile:

**Comment by SiKing** [comment]
Thank You. Beginner's luck? ;)

**Comment by alonswartz** [comment]
Closed due to #29

**Pull request closed without merging**
